### ISSUE TITLE
Is this..., is this legal? What's the best way to solve polymorphism in `ObjectiveFunction`?

### ISSUE THREAD

**Issue by enajx** [real-itu/benchmarking_evolution_and_bo#26]
Is this..., is this legal?

_Originally posted by @miguelgondu in https://github.com/real-itu/benchmarking_evolution_and_bo/pull/24#discussion_r1064197893_

**Comment by miguelgondu** [comment]
Viejos tiempos. :')

**Comment by enajx** [comment]
When men were men and optimisers weren't learned
